### ISSUE TITLE
🚀 [Feature] Frontend: Mobile iFrame Design

### ISSUE THREAD

**Issue by mahula** [dreammall-earth/dreammall.earth#1308]
<img width="376" alt="Screenshot 2024-07-01 at 12 10 00" src="https://github.com/dreammall-earth/dreammall.earth/assets/33051975/9aaa1fce-8c1d-4ea0-b3ee-f5d6e9f68b71">

## 🚀 Feature
As a user on mobile device
I want to interact with the BBB UI
To efficiently use BBB session

### TODO

- [ ] set iFrame bewteen header and bottom menu

**Comment by Bettelstab** [comment]
On master, there is a `margin-top` on `.page-container`, so this does not happen. Still we have to solve this, since that margin generally is too much.

We need to clarify: Do we want the TabControl to be sticky (as in master) or fixed (as on stage1) or should it depend on the page? (I suggest always sticky.)
