### ISSUE TITLE
🚀 [Feature] Delete user in Authentik must be deleted in Dreammall

### ISSUE THREAD

**Issue by ulfgebhardt** [dreammall-earth/dreammall.earth#1790]
## 🚀 Feature

Delete user in Authentik must be deleted in Dreammall

We decided that we use Authentik as administrative interface. Hence we need to reflect decisions made in authentik in our application.

Who: Admin
What: Bans User, User Data must become invisible for everyone (except in authentik)
Why: The Admin might decide to delete users because the produce malicious content - hence we delete the user and want to delete all contents of his.

**Comment by roschaefer** [comment]
I would like to change the requirements here.

This is what Authentik webhooks send after deactivating a user:
```json
{
  "body": "model_updated: {'model': {'pk': 5, 'app': 'authentik_core', 'name': 'What Ever', 'model_name': 'user'}, 'http_request': {'args': {}, 'path': '/api/v3/core/users/5/', 'method': 'PATCH', 'request_id': 'c27363165d4d4dd39fe9b234dc1a7c74', 'user_agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0'}}",
  "severity": "notice",
  "user_email": "admin@dreammall.earth",
  "user_username": "akadmin",
  "event_user_email": "admin@dreammall.earth",
  "event_user_username": "akadmin"
}
```

This is what Authentik webhooks send when you delete a user:
```json
{
  "body": "model_deleted: {'model': {'pk': 5, 'app': 'authentik_core', 'name': 'What Ever', 'model_name': 'user'}, 'http_request': {'args': {}, 'path': '/api/v3/core/users/5/', 'method': 'DELETE', 'request_id': '9bd0288e2fd14681b2cfd0a0a79ae4da', 'user_agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0'}}",
  "severity": "notice",
  "user_email": "admin@dreammall.earth",
  "user_username": "akadmin",
  "event_user_email": "admin@dreammall.earth",
  "event_user_username": "akadmin"
}
```

I don't know why the payload does not contain **what** has changed for `model_updated`. Was the user deactivated? Or did he just update his name? Probably, we can get this through another API request.

But this makes me reconsider the feature itself. A soft-delete is actually separate feature, isn't it? We haven't implemented hard-delete, yet. Here's my suggestion:

**Implement hard-delete first. Implement soft-delete when we actually need it.**

The important requirement is: "Make the user content go away." This is covered if we implement a hard-delete. Implementing soft-delete brings in a lot of complexity, because every resolver in our backend would need to filter for `disabled: true`. This adds potential for bugs.

There is also another reason to go for hard-delete first: GDPR. It requires us to delete user data on request. A soft-delete is not enough and if we change this requirement, we would check this box, too.

**Comment by roschaefer** [comment]
done via #2258
