### ISSUE TITLE
🐛 [Bug] Frontend: On long Self Descriptions Cockpit has a Display Error

### ISSUE THREAD

**Issue by Tirokk** [dreammall-earth/dreammall.earth#2572]
## 🐛 Bug

On long Self Descriptions Cockpit has a Display Error.

<img width="874" alt="Bildschirmfoto 2024-10-03 um 20 22 10" src="https://github.com/user-attachments/assets/304023b9-3c8c-4134-a6db-c138943bd7c6">

**Comment by ogerly** [comment]
In the first line you can see two labels each with the stud cap icon, below where the problem is, there are probably three things behind one icon. Why is that? What kind of logic is that?
For the sake of order and clarity, it would make sense to have the same icon for each group, but to list the things individually. As it is now, it is not selectable as a hashtag if there is more than one word in it.
Or are they not hashtags?

**Comment by ulfgebhardt** [comment]
Limit maximum size, three dots

**Comment by Tirokk** [comment]
Hey @Bettelstab ,
may be there is another solution as well. That we can if we are in edit mode.
If you like, please contact me.
