### ISSUE TITLE
🚀 [Feature] Frontend: Leave BBB room

### ISSUE THREAD

**Issue by Elweyn** [dreammall-earth/dreammall.earth#706]
## 🚀 Feature

We want the frontend to register when the User leaves BigBlueButton table.
:warning: This has been postponed due to several infrastructure issue, which have to be addressed first.

In the backend a redirect url when a meeting is ended to (eg. https://stage1.app.dreammall.earth/ or a new page)

## 🤖 ToDo

- [x] Redirect to home

**Comment by Bettelstab** [comment]
Unfortunately the iframe src does not change when its location changes, as I had expected. It seems there is no way for the parent to detect the location change by itself, because of browsers' Same Origin Policy.
What we can do, hopefully, is to send a message via postMessage. That means we need to modify BigBlueButton code and I currently don't know how to do that
